/*
 * eodhistoricaldata
 *
 * eodhistoricaldata API
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// FundamentalsEarningsTrend struct for FundamentalsEarningsTrend
type FundamentalsEarningsTrend struct {
	Date                             *string `json:"date,omitempty"`
	Period                           *string `json:"period,omitempty"`
	Growth                           *string `json:"growth,omitempty"`
	EarningsEstimateAvg              *string `json:"earningsEstimateAvg,omitempty"`
	EarningsEstimateLow              *string `json:"earningsEstimateLow,omitempty"`
	EarningsEstimateHigh             *string `json:"earningsEstimateHigh,omitempty"`
	EarningsEstimateYearAgoEps       *string `json:"earningsEstimateYearAgoEps,omitempty"`
	EarningsEstimateNumberOfAnalysts *string `json:"earningsEstimateNumberOfAnalysts,omitempty"`
	EarningsEstimateGrowth           *string `json:"earningsEstimateGrowth,omitempty"`
	RevenueEstimateAvg               *string `json:"revenueEstimateAvg,omitempty"`
	RevenueEstimateLow               *string `json:"revenueEstimateLow,omitempty"`
	RevenueEstimateHigh              *string `json:"revenueEstimateHigh,omitempty"`
	RevenueEstimateYearAgoEps        *string `json:"revenueEstimateYearAgoEps,omitempty"`
	RevenueEstimateNumberOfAnalysts  *string `json:"revenueEstimateNumberOfAnalysts,omitempty"`
	RevenueEstimateGrowth            *string `json:"revenueEstimateGrowth,omitempty"`
	EpsTrendCurrent                  *string `json:"epsTrendCurrent,omitempty"`
	EpsTrend7daysAgo                 *string `json:"epsTrend7daysAgo,omitempty"`
	EpsTrend30daysAgo                *string `json:"epsTrend30daysAgo,omitempty"`
	EpsTrend60daysAgo                *string `json:"epsTrend60daysAgo,omitempty"`
	EpsTrend90daysAgo                *string `json:"epsTrend90daysAgo,omitempty"`
	EpsRevisionsUpLast7days          *string `json:"epsRevisionsUpLast7days,omitempty"`
	EpsRevisionsUpLast30days         *string `json:"epsRevisionsUpLast30days,omitempty"`
	EpsRevisionsDownLast30days       *string `json:"epsRevisionsDownLast30days,omitempty"`
	EpsRevisionsDownLast90days       *string `json:"epsRevisionsDownLast90days,omitempty"`
}

// NewFundamentalsEarningsTrend instantiates a new FundamentalsEarningsTrend object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFundamentalsEarningsTrend() *FundamentalsEarningsTrend {
	this := FundamentalsEarningsTrend{}
	return &this
}

// NewFundamentalsEarningsTrendWithDefaults instantiates a new FundamentalsEarningsTrend object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFundamentalsEarningsTrendWithDefaults() *FundamentalsEarningsTrend {
	this := FundamentalsEarningsTrend{}
	return &this
}

// GetDate returns the Date field value if set, zero value otherwise.
func (o *FundamentalsEarningsTrend) GetDate() string {
	if o == nil || o.Date == nil {
		var ret string
		return ret
	}
	return *o.Date
}

// GetDateOk returns a tuple with the Date field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FundamentalsEarningsTrend) GetDateOk() (*string, bool) {
	if o == nil || o.Date == nil {
		return nil, false
	}
	return o.Date, true
}

// HasDate returns a boolean if a field has been set.
func (o *FundamentalsEarningsTrend) HasDate() bool {
	if o != nil && o.Date != nil {
		return true
	}

	return false
}

// SetDate gets a reference to the given string and assigns it to the Date field.
func (o *FundamentalsEarningsTrend) SetDate(v string) {
	o.Date = &v
}

// GetPeriod returns the Period field value if set, zero value otherwise.
func (o *FundamentalsEarningsTrend) GetPeriod() string {
	if o == nil || o.Period == nil {
		var ret string
		return ret
	}
	return *o.Period
}

// GetPeriodOk returns a tuple with the Period field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FundamentalsEarningsTrend) GetPeriodOk() (*string, bool) {
	if o == nil || o.Period == nil {
		return nil, false
	}
	return o.Period, true
}

// HasPeriod returns a boolean if a field has been set.
func (o *FundamentalsEarningsTrend) HasPeriod() bool {
	if o != nil && o.Period != nil {
		return true
	}

	return false
}

// SetPeriod gets a reference to the given string and assigns it to the Period field.
func (o *FundamentalsEarningsTrend) SetPeriod(v string) {
	o.Period = &v
}

// GetGrowth returns the Growth field value if set, zero value otherwise.
func (o *FundamentalsEarningsTrend) GetGrowth() string {
	if o == nil || o.Growth == nil {
		var ret string
		return ret
	}
	return *o.Growth
}

// GetGrowthOk returns a tuple with the Growth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FundamentalsEarningsTrend) GetGrowthOk() (*string, bool) {
	if o == nil || o.Growth == nil {
		return nil, false
	}
	return o.Growth, true
}

// HasGrowth returns a boolean if a field has been set.
func (o *FundamentalsEarningsTrend) HasGrowth() bool {
	if o != nil && o.Growth != nil {
		return true
	}

	return false
}

// SetGrowth gets a reference to the given string and assigns it to the Growth field.
func (o *FundamentalsEarningsTrend) SetGrowth(v string) {
	o.Growth = &v
}

// GetEarningsEstimateAvg returns the EarningsEstimateAvg field value if set, zero value otherwise.
func (o *FundamentalsEarningsTrend) GetEarningsEstimateAvg() string {
	if o == nil || o.EarningsEstimateAvg == nil {
		var ret string
		return ret
	}
	return *o.EarningsEstimateAvg
}

// GetEarningsEstimateAvgOk returns a tuple with the EarningsEstimateAvg field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FundamentalsEarningsTrend) GetEarningsEstimateAvgOk() (*string, bool) {
	if o == nil || o.EarningsEstimateAvg == nil {
		return nil, false
	}
	return o.EarningsEstimateAvg, true
}

// HasEarningsEstimateAvg returns a boolean if a field has been set.
func (o *FundamentalsEarningsTrend) HasEarningsEstimateAvg() bool {
	if o != nil && o.EarningsEstimateAvg != nil {
		return true
	}

	return false
}

// SetEarningsEstimateAvg gets a reference to the given string and assigns it to the EarningsEstimateAvg field.
func (o *FundamentalsEarningsTrend) SetEarningsEstimateAvg(v string) {
	o.EarningsEstimateAvg = &v
}

// GetEarningsEstimateLow returns the EarningsEstimateLow field value if set, zero value otherwise.
func (o *FundamentalsEarningsTrend) GetEarningsEstimateLow() string {
	if o == nil || o.EarningsEstimateLow == nil {
		var ret string
		return ret
	}
	return *o.EarningsEstimateLow
}

// GetEarningsEstimateLowOk returns a tuple with the EarningsEstimateLow field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FundamentalsEarningsTrend) GetEarningsEstimateLowOk() (*string, bool) {
	if o == nil || o.EarningsEstimateLow == nil {
		return nil, false
	}
	return o.EarningsEstimateLow, true
}

// HasEarningsEstimateLow returns a boolean if a field has been set.
func (o *FundamentalsEarningsTrend) HasEarningsEstimateLow() bool {
	if o != nil && o.EarningsEstimateLow != nil {
		return true
	}

	return false
}

// SetEarningsEstimateLow gets a reference to the given string and assigns it to the EarningsEstimateLow field.
func (o *FundamentalsEarningsTrend) SetEarningsEstimateLow(v string) {
	o.EarningsEstimateLow = &v
}

// GetEarningsEstimateHigh returns the EarningsEstimateHigh field value if set, zero value otherwise.
func (o *FundamentalsEarningsTrend) GetEarningsEstimateHigh() string {
	if o == nil || o.EarningsEstimateHigh == nil {
		var ret string
		return ret
	}
	return *o.EarningsEstimateHigh
}

// GetEarningsEstimateHighOk returns a tuple with the EarningsEstimateHigh field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FundamentalsEarningsTrend) GetEarningsEstimateHighOk() (*string, bool) {
	if o == nil || o.EarningsEstimateHigh == nil {
		return nil, false
	}
	return o.EarningsEstimateHigh, true
}

// HasEarningsEstimateHigh returns a boolean if a field has been set.
func (o *FundamentalsEarningsTrend) HasEarningsEstimateHigh() bool {
	if o != nil && o.EarningsEstimateHigh != nil {
		return true
	}

	return false
}

// SetEarningsEstimateHigh gets a reference to the given string and assigns it to the EarningsEstimateHigh field.
func (o *FundamentalsEarningsTrend) SetEarningsEstimateHigh(v string) {
	o.EarningsEstimateHigh = &v
}

// GetEarningsEstimateYearAgoEps returns the EarningsEstimateYearAgoEps field value if set, zero value otherwise.
func (o *FundamentalsEarningsTrend) GetEarningsEstimateYearAgoEps() string {
	if o == nil || o.EarningsEstimateYearAgoEps == nil {
		var ret string
		return ret
	}
	return *o.EarningsEstimateYearAgoEps
}

// GetEarningsEstimateYearAgoEpsOk returns a tuple with the EarningsEstimateYearAgoEps field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FundamentalsEarningsTrend) GetEarningsEstimateYearAgoEpsOk() (*string, bool) {
	if o == nil || o.EarningsEstimateYearAgoEps == nil {
		return nil, false
	}
	return o.EarningsEstimateYearAgoEps, true
}

// HasEarningsEstimateYearAgoEps returns a boolean if a field has been set.
func (o *FundamentalsEarningsTrend) HasEarningsEstimateYearAgoEps() bool {
	if o != nil && o.EarningsEstimateYearAgoEps != nil {
		return true
	}

	return false
}

// SetEarningsEstimateYearAgoEps gets a reference to the given string and assigns it to the EarningsEstimateYearAgoEps field.
func (o *FundamentalsEarningsTrend) SetEarningsEstimateYearAgoEps(v string) {
	o.EarningsEstimateYearAgoEps = &v
}

// GetEarningsEstimateNumberOfAnalysts returns the EarningsEstimateNumberOfAnalysts field value if set, zero value otherwise.
func (o *FundamentalsEarningsTrend) GetEarningsEstimateNumberOfAnalysts() string {
	if o == nil || o.EarningsEstimateNumberOfAnalysts == nil {
		var ret string
		return ret
	}
	return *o.EarningsEstimateNumberOfAnalysts
}

// GetEarningsEstimateNumberOfAnalystsOk returns a tuple with the EarningsEstimateNumberOfAnalysts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FundamentalsEarningsTrend) GetEarningsEstimateNumberOfAnalystsOk() (*string, bool) {
	if o == nil || o.EarningsEstimateNumberOfAnalysts == nil {
		return nil, false
	}
	return o.EarningsEstimateNumberOfAnalysts, true
}

// HasEarningsEstimateNumberOfAnalysts returns a boolean if a field has been set.
func (o *FundamentalsEarningsTrend) HasEarningsEstimateNumberOfAnalysts() bool {
	if o != nil && o.EarningsEstimateNumberOfAnalysts != nil {
		return true
	}

	return false
}

// SetEarningsEstimateNumberOfAnalysts gets a reference to the given string and assigns it to the EarningsEstimateNumberOfAnalysts field.
func (o *FundamentalsEarningsTrend) SetEarningsEstimateNumberOfAnalysts(v string) {
	o.EarningsEstimateNumberOfAnalysts = &v
}

// GetEarningsEstimateGrowth returns the EarningsEstimateGrowth field value if set, zero value otherwise.
func (o *FundamentalsEarningsTrend) GetEarningsEstimateGrowth() string {
	if o == nil || o.EarningsEstimateGrowth == nil {
		var ret string
		return ret
	}
	return *o.EarningsEstimateGrowth
}

// GetEarningsEstimateGrowthOk returns a tuple with the EarningsEstimateGrowth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FundamentalsEarningsTrend) GetEarningsEstimateGrowthOk() (*string, bool) {
	if o == nil || o.EarningsEstimateGrowth == nil {
		return nil, false
	}
	return o.EarningsEstimateGrowth, true
}

// HasEarningsEstimateGrowth returns a boolean if a field has been set.
func (o *FundamentalsEarningsTrend) HasEarningsEstimateGrowth() bool {
	if o != nil && o.EarningsEstimateGrowth != nil {
		return true
	}

	return false
}

// SetEarningsEstimateGrowth gets a reference to the given string and assigns it to the EarningsEstimateGrowth field.
func (o *FundamentalsEarningsTrend) SetEarningsEstimateGrowth(v string) {
	o.EarningsEstimateGrowth = &v
}

// GetRevenueEstimateAvg returns the RevenueEstimateAvg field value if set, zero value otherwise.
func (o *FundamentalsEarningsTrend) GetRevenueEstimateAvg() string {
	if o == nil || o.RevenueEstimateAvg == nil {
		var ret string
		return ret
	}
	return *o.RevenueEstimateAvg
}

// GetRevenueEstimateAvgOk returns a tuple with the RevenueEstimateAvg field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FundamentalsEarningsTrend) GetRevenueEstimateAvgOk() (*string, bool) {
	if o == nil || o.RevenueEstimateAvg == nil {
		return nil, false
	}
	return o.RevenueEstimateAvg, true
}

// HasRevenueEstimateAvg returns a boolean if a field has been set.
func (o *FundamentalsEarningsTrend) HasRevenueEstimateAvg() bool {
	if o != nil && o.RevenueEstimateAvg != nil {
		return true
	}

	return false
}

// SetRevenueEstimateAvg gets a reference to the given string and assigns it to the RevenueEstimateAvg field.
func (o *FundamentalsEarningsTrend) SetRevenueEstimateAvg(v string) {
	o.RevenueEstimateAvg = &v
}

// GetRevenueEstimateLow returns the RevenueEstimateLow field value if set, zero value otherwise.
func (o *FundamentalsEarningsTrend) GetRevenueEstimateLow() string {
	if o == nil || o.RevenueEstimateLow == nil {
		var ret string
		return ret
	}
	return *o.RevenueEstimateLow
}

// GetRevenueEstimateLowOk returns a tuple with the RevenueEstimateLow field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FundamentalsEarningsTrend) GetRevenueEstimateLowOk() (*string, bool) {
	if o == nil || o.RevenueEstimateLow == nil {
		return nil, false
	}
	return o.RevenueEstimateLow, true
}

// HasRevenueEstimateLow returns a boolean if a field has been set.
func (o *FundamentalsEarningsTrend) HasRevenueEstimateLow() bool {
	if o != nil && o.RevenueEstimateLow != nil {
		return true
	}

	return false
}

// SetRevenueEstimateLow gets a reference to the given string and assigns it to the RevenueEstimateLow field.
func (o *FundamentalsEarningsTrend) SetRevenueEstimateLow(v string) {
	o.RevenueEstimateLow = &v
}

// GetRevenueEstimateHigh returns the RevenueEstimateHigh field value if set, zero value otherwise.
func (o *FundamentalsEarningsTrend) GetRevenueEstimateHigh() string {
	if o == nil || o.RevenueEstimateHigh == nil {
		var ret string
		return ret
	}
	return *o.RevenueEstimateHigh
}

// GetRevenueEstimateHighOk returns a tuple with the RevenueEstimateHigh field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FundamentalsEarningsTrend) GetRevenueEstimateHighOk() (*string, bool) {
	if o == nil || o.RevenueEstimateHigh == nil {
		return nil, false
	}
	return o.RevenueEstimateHigh, true
}

// HasRevenueEstimateHigh returns a boolean if a field has been set.
func (o *FundamentalsEarningsTrend) HasRevenueEstimateHigh() bool {
	if o != nil && o.RevenueEstimateHigh != nil {
		return true
	}

	return false
}

// SetRevenueEstimateHigh gets a reference to the given string and assigns it to the RevenueEstimateHigh field.
func (o *FundamentalsEarningsTrend) SetRevenueEstimateHigh(v string) {
	o.RevenueEstimateHigh = &v
}

// GetRevenueEstimateYearAgoEps returns the RevenueEstimateYearAgoEps field value if set, zero value otherwise.
func (o *FundamentalsEarningsTrend) GetRevenueEstimateYearAgoEps() string {
	if o == nil || o.RevenueEstimateYearAgoEps == nil {
		var ret string
		return ret
	}
	return *o.RevenueEstimateYearAgoEps
}

// GetRevenueEstimateYearAgoEpsOk returns a tuple with the RevenueEstimateYearAgoEps field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FundamentalsEarningsTrend) GetRevenueEstimateYearAgoEpsOk() (*string, bool) {
	if o == nil || o.RevenueEstimateYearAgoEps == nil {
		return nil, false
	}
	return o.RevenueEstimateYearAgoEps, true
}

// HasRevenueEstimateYearAgoEps returns a boolean if a field has been set.
func (o *FundamentalsEarningsTrend) HasRevenueEstimateYearAgoEps() bool {
	if o != nil && o.RevenueEstimateYearAgoEps != nil {
		return true
	}

	return false
}

// SetRevenueEstimateYearAgoEps gets a reference to the given string and assigns it to the RevenueEstimateYearAgoEps field.
func (o *FundamentalsEarningsTrend) SetRevenueEstimateYearAgoEps(v string) {
	o.RevenueEstimateYearAgoEps = &v
}

// GetRevenueEstimateNumberOfAnalysts returns the RevenueEstimateNumberOfAnalysts field value if set, zero value otherwise.
func (o *FundamentalsEarningsTrend) GetRevenueEstimateNumberOfAnalysts() string {
	if o == nil || o.RevenueEstimateNumberOfAnalysts == nil {
		var ret string
		return ret
	}
	return *o.RevenueEstimateNumberOfAnalysts
}

// GetRevenueEstimateNumberOfAnalystsOk returns a tuple with the RevenueEstimateNumberOfAnalysts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FundamentalsEarningsTrend) GetRevenueEstimateNumberOfAnalystsOk() (*string, bool) {
	if o == nil || o.RevenueEstimateNumberOfAnalysts == nil {
		return nil, false
	}
	return o.RevenueEstimateNumberOfAnalysts, true
}

// HasRevenueEstimateNumberOfAnalysts returns a boolean if a field has been set.
func (o *FundamentalsEarningsTrend) HasRevenueEstimateNumberOfAnalysts() bool {
	if o != nil && o.RevenueEstimateNumberOfAnalysts != nil {
		return true
	}

	return false
}

// SetRevenueEstimateNumberOfAnalysts gets a reference to the given string and assigns it to the RevenueEstimateNumberOfAnalysts field.
func (o *FundamentalsEarningsTrend) SetRevenueEstimateNumberOfAnalysts(v string) {
	o.RevenueEstimateNumberOfAnalysts = &v
}

// GetRevenueEstimateGrowth returns the RevenueEstimateGrowth field value if set, zero value otherwise.
func (o *FundamentalsEarningsTrend) GetRevenueEstimateGrowth() string {
	if o == nil || o.RevenueEstimateGrowth == nil {
		var ret string
		return ret
	}
	return *o.RevenueEstimateGrowth
}

// GetRevenueEstimateGrowthOk returns a tuple with the RevenueEstimateGrowth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FundamentalsEarningsTrend) GetRevenueEstimateGrowthOk() (*string, bool) {
	if o == nil || o.RevenueEstimateGrowth == nil {
		return nil, false
	}
	return o.RevenueEstimateGrowth, true
}

// HasRevenueEstimateGrowth returns a boolean if a field has been set.
func (o *FundamentalsEarningsTrend) HasRevenueEstimateGrowth() bool {
	if o != nil && o.RevenueEstimateGrowth != nil {
		return true
	}

	return false
}

// SetRevenueEstimateGrowth gets a reference to the given string and assigns it to the RevenueEstimateGrowth field.
func (o *FundamentalsEarningsTrend) SetRevenueEstimateGrowth(v string) {
	o.RevenueEstimateGrowth = &v
}

// GetEpsTrendCurrent returns the EpsTrendCurrent field value if set, zero value otherwise.
func (o *FundamentalsEarningsTrend) GetEpsTrendCurrent() string {
	if o == nil || o.EpsTrendCurrent == nil {
		var ret string
		return ret
	}
	return *o.EpsTrendCurrent
}

// GetEpsTrendCurrentOk returns a tuple with the EpsTrendCurrent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FundamentalsEarningsTrend) GetEpsTrendCurrentOk() (*string, bool) {
	if o == nil || o.EpsTrendCurrent == nil {
		return nil, false
	}
	return o.EpsTrendCurrent, true
}

// HasEpsTrendCurrent returns a boolean if a field has been set.
func (o *FundamentalsEarningsTrend) HasEpsTrendCurrent() bool {
	if o != nil && o.EpsTrendCurrent != nil {
		return true
	}

	return false
}

// SetEpsTrendCurrent gets a reference to the given string and assigns it to the EpsTrendCurrent field.
func (o *FundamentalsEarningsTrend) SetEpsTrendCurrent(v string) {
	o.EpsTrendCurrent = &v
}

// GetEpsTrend7daysAgo returns the EpsTrend7daysAgo field value if set, zero value otherwise.
func (o *FundamentalsEarningsTrend) GetEpsTrend7daysAgo() string {
	if o == nil || o.EpsTrend7daysAgo == nil {
		var ret string
		return ret
	}
	return *o.EpsTrend7daysAgo
}

// GetEpsTrend7daysAgoOk returns a tuple with the EpsTrend7daysAgo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FundamentalsEarningsTrend) GetEpsTrend7daysAgoOk() (*string, bool) {
	if o == nil || o.EpsTrend7daysAgo == nil {
		return nil, false
	}
	return o.EpsTrend7daysAgo, true
}

// HasEpsTrend7daysAgo returns a boolean if a field has been set.
func (o *FundamentalsEarningsTrend) HasEpsTrend7daysAgo() bool {
	if o != nil && o.EpsTrend7daysAgo != nil {
		return true
	}

	return false
}

// SetEpsTrend7daysAgo gets a reference to the given string and assigns it to the EpsTrend7daysAgo field.
func (o *FundamentalsEarningsTrend) SetEpsTrend7daysAgo(v string) {
	o.EpsTrend7daysAgo = &v
}

// GetEpsTrend30daysAgo returns the EpsTrend30daysAgo field value if set, zero value otherwise.
func (o *FundamentalsEarningsTrend) GetEpsTrend30daysAgo() string {
	if o == nil || o.EpsTrend30daysAgo == nil {
		var ret string
		return ret
	}
	return *o.EpsTrend30daysAgo
}

// GetEpsTrend30daysAgoOk returns a tuple with the EpsTrend30daysAgo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FundamentalsEarningsTrend) GetEpsTrend30daysAgoOk() (*string, bool) {
	if o == nil || o.EpsTrend30daysAgo == nil {
		return nil, false
	}
	return o.EpsTrend30daysAgo, true
}

// HasEpsTrend30daysAgo returns a boolean if a field has been set.
func (o *FundamentalsEarningsTrend) HasEpsTrend30daysAgo() bool {
	if o != nil && o.EpsTrend30daysAgo != nil {
		return true
	}

	return false
}

// SetEpsTrend30daysAgo gets a reference to the given string and assigns it to the EpsTrend30daysAgo field.
func (o *FundamentalsEarningsTrend) SetEpsTrend30daysAgo(v string) {
	o.EpsTrend30daysAgo = &v
}

// GetEpsTrend60daysAgo returns the EpsTrend60daysAgo field value if set, zero value otherwise.
func (o *FundamentalsEarningsTrend) GetEpsTrend60daysAgo() string {
	if o == nil || o.EpsTrend60daysAgo == nil {
		var ret string
		return ret
	}
	return *o.EpsTrend60daysAgo
}

// GetEpsTrend60daysAgoOk returns a tuple with the EpsTrend60daysAgo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FundamentalsEarningsTrend) GetEpsTrend60daysAgoOk() (*string, bool) {
	if o == nil || o.EpsTrend60daysAgo == nil {
		return nil, false
	}
	return o.EpsTrend60daysAgo, true
}

// HasEpsTrend60daysAgo returns a boolean if a field has been set.
func (o *FundamentalsEarningsTrend) HasEpsTrend60daysAgo() bool {
	if o != nil && o.EpsTrend60daysAgo != nil {
		return true
	}

	return false
}

// SetEpsTrend60daysAgo gets a reference to the given string and assigns it to the EpsTrend60daysAgo field.
func (o *FundamentalsEarningsTrend) SetEpsTrend60daysAgo(v string) {
	o.EpsTrend60daysAgo = &v
}

// GetEpsTrend90daysAgo returns the EpsTrend90daysAgo field value if set, zero value otherwise.
func (o *FundamentalsEarningsTrend) GetEpsTrend90daysAgo() string {
	if o == nil || o.EpsTrend90daysAgo == nil {
		var ret string
		return ret
	}
	return *o.EpsTrend90daysAgo
}

// GetEpsTrend90daysAgoOk returns a tuple with the EpsTrend90daysAgo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FundamentalsEarningsTrend) GetEpsTrend90daysAgoOk() (*string, bool) {
	if o == nil || o.EpsTrend90daysAgo == nil {
		return nil, false
	}
	return o.EpsTrend90daysAgo, true
}

// HasEpsTrend90daysAgo returns a boolean if a field has been set.
func (o *FundamentalsEarningsTrend) HasEpsTrend90daysAgo() bool {
	if o != nil && o.EpsTrend90daysAgo != nil {
		return true
	}

	return false
}

// SetEpsTrend90daysAgo gets a reference to the given string and assigns it to the EpsTrend90daysAgo field.
func (o *FundamentalsEarningsTrend) SetEpsTrend90daysAgo(v string) {
	o.EpsTrend90daysAgo = &v
}

// GetEpsRevisionsUpLast7days returns the EpsRevisionsUpLast7days field value if set, zero value otherwise.
func (o *FundamentalsEarningsTrend) GetEpsRevisionsUpLast7days() string {
	if o == nil || o.EpsRevisionsUpLast7days == nil {
		var ret string
		return ret
	}
	return *o.EpsRevisionsUpLast7days
}

// GetEpsRevisionsUpLast7daysOk returns a tuple with the EpsRevisionsUpLast7days field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FundamentalsEarningsTrend) GetEpsRevisionsUpLast7daysOk() (*string, bool) {
	if o == nil || o.EpsRevisionsUpLast7days == nil {
		return nil, false
	}
	return o.EpsRevisionsUpLast7days, true
}

// HasEpsRevisionsUpLast7days returns a boolean if a field has been set.
func (o *FundamentalsEarningsTrend) HasEpsRevisionsUpLast7days() bool {
	if o != nil && o.EpsRevisionsUpLast7days != nil {
		return true
	}

	return false
}

// SetEpsRevisionsUpLast7days gets a reference to the given string and assigns it to the EpsRevisionsUpLast7days field.
func (o *FundamentalsEarningsTrend) SetEpsRevisionsUpLast7days(v string) {
	o.EpsRevisionsUpLast7days = &v
}

// GetEpsRevisionsUpLast30days returns the EpsRevisionsUpLast30days field value if set, zero value otherwise.
func (o *FundamentalsEarningsTrend) GetEpsRevisionsUpLast30days() string {
	if o == nil || o.EpsRevisionsUpLast30days == nil {
		var ret string
		return ret
	}
	return *o.EpsRevisionsUpLast30days
}

// GetEpsRevisionsUpLast30daysOk returns a tuple with the EpsRevisionsUpLast30days field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FundamentalsEarningsTrend) GetEpsRevisionsUpLast30daysOk() (*string, bool) {
	if o == nil || o.EpsRevisionsUpLast30days == nil {
		return nil, false
	}
	return o.EpsRevisionsUpLast30days, true
}

// HasEpsRevisionsUpLast30days returns a boolean if a field has been set.
func (o *FundamentalsEarningsTrend) HasEpsRevisionsUpLast30days() bool {
	if o != nil && o.EpsRevisionsUpLast30days != nil {
		return true
	}

	return false
}

// SetEpsRevisionsUpLast30days gets a reference to the given string and assigns it to the EpsRevisionsUpLast30days field.
func (o *FundamentalsEarningsTrend) SetEpsRevisionsUpLast30days(v string) {
	o.EpsRevisionsUpLast30days = &v
}

// GetEpsRevisionsDownLast30days returns the EpsRevisionsDownLast30days field value if set, zero value otherwise.
func (o *FundamentalsEarningsTrend) GetEpsRevisionsDownLast30days() string {
	if o == nil || o.EpsRevisionsDownLast30days == nil {
		var ret string
		return ret
	}
	return *o.EpsRevisionsDownLast30days
}

// GetEpsRevisionsDownLast30daysOk returns a tuple with the EpsRevisionsDownLast30days field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FundamentalsEarningsTrend) GetEpsRevisionsDownLast30daysOk() (*string, bool) {
	if o == nil || o.EpsRevisionsDownLast30days == nil {
		return nil, false
	}
	return o.EpsRevisionsDownLast30days, true
}

// HasEpsRevisionsDownLast30days returns a boolean if a field has been set.
func (o *FundamentalsEarningsTrend) HasEpsRevisionsDownLast30days() bool {
	if o != nil && o.EpsRevisionsDownLast30days != nil {
		return true
	}

	return false
}

// SetEpsRevisionsDownLast30days gets a reference to the given string and assigns it to the EpsRevisionsDownLast30days field.
func (o *FundamentalsEarningsTrend) SetEpsRevisionsDownLast30days(v string) {
	o.EpsRevisionsDownLast30days = &v
}

// GetEpsRevisionsDownLast90days returns the EpsRevisionsDownLast90days field value if set, zero value otherwise.
func (o *FundamentalsEarningsTrend) GetEpsRevisionsDownLast90days() string {
	if o == nil || o.EpsRevisionsDownLast90days == nil {
		var ret string
		return ret
	}
	return *o.EpsRevisionsDownLast90days
}

// GetEpsRevisionsDownLast90daysOk returns a tuple with the EpsRevisionsDownLast90days field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FundamentalsEarningsTrend) GetEpsRevisionsDownLast90daysOk() (*string, bool) {
	if o == nil || o.EpsRevisionsDownLast90days == nil {
		return nil, false
	}
	return o.EpsRevisionsDownLast90days, true
}

// HasEpsRevisionsDownLast90days returns a boolean if a field has been set.
func (o *FundamentalsEarningsTrend) HasEpsRevisionsDownLast90days() bool {
	if o != nil && o.EpsRevisionsDownLast90days != nil {
		return true
	}

	return false
}

// SetEpsRevisionsDownLast90days gets a reference to the given string and assigns it to the EpsRevisionsDownLast90days field.
func (o *FundamentalsEarningsTrend) SetEpsRevisionsDownLast90days(v string) {
	o.EpsRevisionsDownLast90days = &v
}

func (o FundamentalsEarningsTrend) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Date != nil {
		toSerialize["date"] = o.Date
	}
	if o.Period != nil {
		toSerialize["period"] = o.Period
	}
	if o.Growth != nil {
		toSerialize["growth"] = o.Growth
	}
	if o.EarningsEstimateAvg != nil {
		toSerialize["earningsEstimateAvg"] = o.EarningsEstimateAvg
	}
	if o.EarningsEstimateLow != nil {
		toSerialize["earningsEstimateLow"] = o.EarningsEstimateLow
	}
	if o.EarningsEstimateHigh != nil {
		toSerialize["earningsEstimateHigh"] = o.EarningsEstimateHigh
	}
	if o.EarningsEstimateYearAgoEps != nil {
		toSerialize["earningsEstimateYearAgoEps"] = o.EarningsEstimateYearAgoEps
	}
	if o.EarningsEstimateNumberOfAnalysts != nil {
		toSerialize["earningsEstimateNumberOfAnalysts"] = o.EarningsEstimateNumberOfAnalysts
	}
	if o.EarningsEstimateGrowth != nil {
		toSerialize["earningsEstimateGrowth"] = o.EarningsEstimateGrowth
	}
	if o.RevenueEstimateAvg != nil {
		toSerialize["revenueEstimateAvg"] = o.RevenueEstimateAvg
	}
	if o.RevenueEstimateLow != nil {
		toSerialize["revenueEstimateLow"] = o.RevenueEstimateLow
	}
	if o.RevenueEstimateHigh != nil {
		toSerialize["revenueEstimateHigh"] = o.RevenueEstimateHigh
	}
	if o.RevenueEstimateYearAgoEps != nil {
		toSerialize["revenueEstimateYearAgoEps"] = o.RevenueEstimateYearAgoEps
	}
	if o.RevenueEstimateNumberOfAnalysts != nil {
		toSerialize["revenueEstimateNumberOfAnalysts"] = o.RevenueEstimateNumberOfAnalysts
	}
	if o.RevenueEstimateGrowth != nil {
		toSerialize["revenueEstimateGrowth"] = o.RevenueEstimateGrowth
	}
	if o.EpsTrendCurrent != nil {
		toSerialize["epsTrendCurrent"] = o.EpsTrendCurrent
	}
	if o.EpsTrend7daysAgo != nil {
		toSerialize["epsTrend7daysAgo"] = o.EpsTrend7daysAgo
	}
	if o.EpsTrend30daysAgo != nil {
		toSerialize["epsTrend30daysAgo"] = o.EpsTrend30daysAgo
	}
	if o.EpsTrend60daysAgo != nil {
		toSerialize["epsTrend60daysAgo"] = o.EpsTrend60daysAgo
	}
	if o.EpsTrend90daysAgo != nil {
		toSerialize["epsTrend90daysAgo"] = o.EpsTrend90daysAgo
	}
	if o.EpsRevisionsUpLast7days != nil {
		toSerialize["epsRevisionsUpLast7days"] = o.EpsRevisionsUpLast7days
	}
	if o.EpsRevisionsUpLast30days != nil {
		toSerialize["epsRevisionsUpLast30days"] = o.EpsRevisionsUpLast30days
	}
	if o.EpsRevisionsDownLast30days != nil {
		toSerialize["epsRevisionsDownLast30days"] = o.EpsRevisionsDownLast30days
	}
	if o.EpsRevisionsDownLast90days != nil {
		toSerialize["epsRevisionsDownLast90days"] = o.EpsRevisionsDownLast90days
	}
	return json.Marshal(toSerialize)
}

type NullableFundamentalsEarningsTrend struct {
	value *FundamentalsEarningsTrend
	isSet bool
}

func (v NullableFundamentalsEarningsTrend) Get() *FundamentalsEarningsTrend {
	return v.value
}

func (v *NullableFundamentalsEarningsTrend) Set(val *FundamentalsEarningsTrend) {
	v.value = val
	v.isSet = true
}

func (v NullableFundamentalsEarningsTrend) IsSet() bool {
	return v.isSet
}

func (v *NullableFundamentalsEarningsTrend) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFundamentalsEarningsTrend(val *FundamentalsEarningsTrend) *NullableFundamentalsEarningsTrend {
	return &NullableFundamentalsEarningsTrend{value: val, isSet: true}
}

func (v NullableFundamentalsEarningsTrend) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFundamentalsEarningsTrend) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
